terraform {
    source = "../modules/APM"
}
# include {
#     path = find_in_parent_folders()
# }
locals {
    account = get_env("ACCOUNT_ID")
    datadog_module = get_env("DATADOG_MODULE")
}
remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }

  config = {
    bucket = "spn-terraform-tfstate"
    key = "${path_relative_to_include()}/${local.account}/${local.datadog_module}/terraform.tfstate"
    region         = "ap-south-1"
    encrypt        = true
    dynamodb_table = "terraform-lock-table"
   } 
}

inputs ={
# region = "ap-south-1"
datadog_site = "datadoghq.com"
APM_service_name = [
                        { 
                        "service_name" : "gv2-priority",
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "http",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "http.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" : "@slack-godavari-beacon-api-tech-alerts",
                        "notification_channel" : "@slack-godavari-beacon-api-tech-alerts @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "gv2-batched",
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "http",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "http.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" : "@slack-godavari-beacon-api-tech-alerts",
                        "notification_channel" : "@slack-godavari-beacon-api-tech-alerts @webhook-DD-Squadcast-Integration"
                    },
                      { 
                        "service_name" : "proxy-service", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "express",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "express.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-usm_tech_alerts",
                        "notification_channel" : "@slack-usm_tech_alerts @webhook-DD-Squadcast-Integration"
                    },
                     { 
                        "service_name" : "mweb", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "express",
                        "apm_latency_metric" : "60",
                        "apm_error_rate_type" : "express.request",
                        "apm_error_rate_metric" : "40",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" : "@slack-spni_mweb_tech_alerts",
                        "notification_channel" : "@slack-spni_mweb_tech_alerts @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "web", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "http",
                        "apm_latency_metric" : "60",
                        "apm_error_rate_type" : "http.request",
                        "apm_error_rate_metric" : "40",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" : "@slack-spni_web_tech_alerts",
                        "notification_channel" : "@slack-spni_web_tech_alerts @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "td", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "http",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "http.request",
                        "apm_error_rate_metric" : "10",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" : "@slack-targeted-delivery-api-alerts",
                        "notification_channel" : "@slack-targeted-delivery-api-alerts @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "subscription-management", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "http",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "http.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-usm_tech_alerts",
                        "notification_channel" : "@slack-usm_tech_alerts @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "user-management", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "fastify",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "fastify.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-usm_tech_alerts",
                        "notification_channel" : "@slack-usm_tech_alerts @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "b2b-jio-prod", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "express",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "express.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-spni_prod_b2b_alerts",
                        "notification_channel" : "@slack-spni_prod_b2b_alerts @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "b2b-airtel-prod", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "express",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "express.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-spni_prod_b2b_alerts",
                        "notification_channel" : "@slack-spni_prod_b2b_alerts @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "b2b-common-prod", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "express",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "express.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-spni_prod_b2b_alerts",
                        "notification_channel" : "@slack-spni_prod_b2b_alerts @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "b2b-catalog-prod", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "express",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "express.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-spni_prod_b2b_alerts",
                        "notification_channel" : "@slack-spni_prod_b2b_alerts @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "b2b-ingestion-prod", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "express",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "express.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-spni_prod_b2b_alerts",
                        "notification_channel" : "@slack-spni_prod_b2b_alerts @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "b2b-jio-prod-redis", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "redis",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "redis.command",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-spni_prod_b2b_alerts",
                        "notification_channel" : "@slack-spni_prod_b2b_alerts @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "prod-tlb-backend", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "http",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "http.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-tlb-alerts",
                        "notification_channel" : "@slack-tlb-alerts @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "prod-godavari-beaconapi", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "http",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "http.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-spni_prod_godavari_v1_alerts",
                        "notification_channel" : "@slack-spni_prod_godavari_v1_alerts @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "agl-core-prod-umsps", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "express",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "express.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-agl-alerts",
                        "notification_channel" : "@slack-agl-alerts  @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "agl-core-prod-appconfig", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "express",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "express.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-agl-alerts",
                        "notification_channel" : "@slack-agl-alerts  @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "agl-core-prod-default", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "express",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "express.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-agl-alerts",
                        "notification_channel" : "@slack-agl-alerts  @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "agl-core-prod-listing", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "express",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "express.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-agl-alerts",
                        "notification_channel" : "@slack-agl-alerts  @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "agl-core-prod-playback", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "express",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "express.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-agl-alerts",
                        "notification_channel" : "@slack-agl-alerts  @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "agl-core-prod-cont-watch", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "express",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "express.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-agl-alerts",
                        "notification_channel" : "@slack-agl-alerts  @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "sf-live-scheduler", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "fastapi",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "fastapi.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-spni_prod_sf_live_alerts",
                        "notification_channel" : "@slack-spni_prod_sf_live_alerts  @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "sf-live-mediaservice", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "fastapi",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "fastapi.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-spni_prod_sf_live_alerts",
                        "notification_channel" : "@slack-spni_prod_sf_live_alerts  @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "sf-live-orchestrator", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "fastapi",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "fastapi.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-spni_prod_sf_live_alerts",
                        "notification_channel" : "@slack-spni_prod_sf_live_alerts  @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "sf-live-prod-orchestrator-notifications", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "aws",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "aws.sns",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-spni_prod_sf_live_alerts",
                        "notification_channel" : "@slack-spni_prod_sf_live_alerts  @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "prod-config-manager-ve", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "fastapi",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "fastapi.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-spni_prod_config_manager_alerts",
                        "notification_channel" : "@slack-spni_prod_config_manager_alerts  @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "scaler-ui-prod", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "flask",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "flask.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-spni_prod_scaler_alerts",
                        "notification_channel" : "@slack-spni_prod_scaler_alerts  @webhook-DD-Squadcast-Integration"
                    },
                    { 
                        "service_name" : "alb-lcu-ui-prod", 
                        "priority" : 1, 
                        "message" : "APM Alert triggered",
                        "runbook" : "",
                        "query_time_window": "last_5m",
                        "apm_latency_type" : "flask",
                        "apm_latency_metric" : "80",
                        "apm_error_rate_type" : "flask.request",
                        "apm_error_rate_metric" : "5",
                        "latency_query" : "",
                        "error_query" : "",
                        "roster" :"@slack-spni_prod_scaler_alerts",
                        "notification_channel" : "@slack-spni_prod_scaler_alerts  @webhook-DD-Squadcast-Integration"
                    }
]
}