terraform {
    source = "../modules/REDIS_CLOUD"
}
# include {
#     path = find_in_parent_folders()
# }
locals {
    account = get_env("ACCOUNT_ID")
    datadog_module = get_env("DATADOG_MODULE")
}
remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }

  config = {
    bucket = "spn-terraform-tfstate"
    key = "${path_relative_to_include()}/${local.account}/${local.datadog_module}/terraform.tfstate"
    region         = "ap-south-1"
    encrypt        = true
    dynamodb_table = "terraform-lock-table"
   } 
}

inputs ={
# region = "ap-south-1"
datadog_site = "datadoghq.com"
redis_cloud_monitors = [
                        { 
                        "service_name" : "tlb",
                        "component_name" : "tlb",
                        "priority" : 2,
                        "message" : "Redis Cloud Alert triggered",
                        "runbook" : "https://sony-liv.atlassian.net/wiki/x/BAJdHQ",
                        "query_time_window": "last_2m",
                        "rdsc_bdb_avg_latency_threshold_critical" = "5",
                        "rdsc_redis_used_memory_threshold_critical" = "26843545600",
                        "rdsc_bdb_shard_cpu_use_threshold_critical" = "70",
                        "rdsc_bdb_ingress_bytes_threshold_critical" = "1073741824",
                        "rdsc_bdb_egress_bytes_threshold_critical" = "1073741824",
                        "rdsc_node_ingress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_egress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_cpu_idle_threshold_critical" = "30",
                        "rdsc_proxy_cpu_threshold_critical" = "70",
                        "notification_channel" : "@slack-tlb-alerts @webhook-DD-Squadcast-Integration",
                        "roster": "@slack-tlb-alerts",
                        "query" : ""
                      },
                      { 
                        "service_name" : "usm",
                        "component_name" : "usm-subscription",
                        "priority" : 2,
                        "message" : "Redis Cloud Alert triggered",
                        "runbook" : "https://sony-liv.atlassian.net/wiki/x/BAJdHQ",
                        "query_time_window": "last_2m",
                        "rdsc_bdb_avg_latency_threshold_critical" = "5",
                        "rdsc_redis_used_memory_threshold_critical" = "26843545600",
                        "rdsc_bdb_shard_cpu_use_threshold_critical" = "70",
                        "rdsc_bdb_ingress_bytes_threshold_critical" = "1073741824",
                        "rdsc_bdb_egress_bytes_threshold_critical" = "1073741824",
                        "rdsc_node_ingress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_egress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_cpu_idle_threshold_critical" = "30",
                        "rdsc_proxy_cpu_threshold_critical" = "70",
                        "notification_channel" : "@slack-usm_tech_alerts  @webhook-DD-Squadcast-Integration",
                        "roster": "@slack-usm_tech_alerts",
                        "query" : ""
                      },
                      { 
                        "service_name" : "usm",
                        "component_name" : "usm-user-mgmt",
                        "priority" : 2,
                        "message" : "Redis Cloud Alert triggered",
                        "runbook" : "https://sony-liv.atlassian.net/wiki/x/BAJdHQ",
                        "query_time_window": "last_2m",
                        "rdsc_bdb_avg_latency_threshold_critical" = "5",
                        "rdsc_redis_used_memory_threshold_critical" = "26843545600",
                        "rdsc_bdb_shard_cpu_use_threshold_critical" = "70",
                        "rdsc_bdb_ingress_bytes_threshold_critical" = "1073741824",
                        "rdsc_bdb_egress_bytes_threshold_critical" = "1073741824",
                        "rdsc_node_ingress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_egress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_cpu_idle_threshold_critical" = "30",
                        "rdsc_proxy_cpu_threshold_critical" = "70",
                        "notification_channel" : "@slack-usm_tech_alerts  @webhook-DD-Squadcast-Integration",
                        "roster": "@slack-usm_tech_alerts",
                        "query" : ""
                      },
                      { 
                        "service_name" : "usm",
                        "component_name" : "usm-session",
                        "priority" : 2,
                        "message" : "Redis Cloud Alert triggered",
                        "runbook" : "https://sony-liv.atlassian.net/wiki/x/BAJdHQ",
                        "query_time_window": "last_2m",
                        "rdsc_bdb_avg_latency_threshold_critical" = "5",
                        "rdsc_redis_used_memory_threshold_critical" = "26843545600",
                        "rdsc_bdb_shard_cpu_use_threshold_critical" = "70",
                        "rdsc_bdb_ingress_bytes_threshold_critical" = "1073741824",
                        "rdsc_bdb_egress_bytes_threshold_critical" = "1073741824",
                        "rdsc_node_ingress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_egress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_cpu_idle_threshold_critical" = "30",
                        "rdsc_proxy_cpu_threshold_critical" = "70",
                        "notification_channel" : "@slack-usm_tech_alerts  @webhook-DD-Squadcast-Integration",
                        "roster": "@slack-usm_tech_alerts",
                        "query" : ""
                      },
                      { 
                        "service_name" : "agl",
                        "component_name" : "agl-core-appconfig",
                        "priority" : 2,
                        "message" : "Redis Cloud Alert triggered",
                        "runbook" : "https://sony-liv.atlassian.net/wiki/x/BAJdHQ",
                        "query_time_window": "last_2m",
                        "rdsc_bdb_avg_latency_threshold_critical" = "5",
                        "rdsc_redis_used_memory_threshold_critical" = "26843545600",
                        "rdsc_bdb_shard_cpu_use_threshold_critical" = "70",
                        "rdsc_bdb_ingress_bytes_threshold_critical" = "1073741824",
                        "rdsc_bdb_egress_bytes_threshold_critical" = "1073741824",
                        "rdsc_node_ingress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_egress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_cpu_idle_threshold_critical" = "30",
                        "rdsc_proxy_cpu_threshold_critical" = "70",
                        "notification_channel" : "@slack-agl-alerts  @webhook-DD-Squadcast-Integration",
                        "roster": "@slack-agl-alerts",
                        "query" : ""
                      },
                      { 
                        "service_name" : "agl",
                        "component_name" : "agl-core-cont-watch",
                        "priority" : 2,
                        "message" : "Redis Cloud Alert triggered",
                        "runbook" : "https://sony-liv.atlassian.net/wiki/x/BAJdHQ",
                        "query_time_window": "last_2m",
                        "rdsc_bdb_avg_latency_threshold_critical" = "5",
                        "rdsc_redis_used_memory_threshold_critical" = "26843545600",
                        "rdsc_bdb_shard_cpu_use_threshold_critical" = "70",
                        "rdsc_bdb_ingress_bytes_threshold_critical" = "1073741824",
                        "rdsc_bdb_egress_bytes_threshold_critical" = "1073741824",
                        "rdsc_node_ingress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_egress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_cpu_idle_threshold_critical" = "30",
                        "rdsc_proxy_cpu_threshold_critical" = "70",
                        "notification_channel" : "@slack-agl-alerts  @webhook-DD-Squadcast-Integration",
                        "roster": "@slack-agl-alerts",
                        "query" : ""
                      },
                      { 
                        "service_name" : "agl",
                        "component_name" : "agl-core-listing",
                        "priority" : 2,
                        "message" : "Redis Cloud Alert triggered",
                        "runbook" : "https://sony-liv.atlassian.net/wiki/x/BAJdHQ",
                        "query_time_window": "last_2m",
                        "rdsc_bdb_avg_latency_threshold_critical" = "5",
                        "rdsc_redis_used_memory_threshold_critical" = "26843545600",
                        "rdsc_bdb_shard_cpu_use_threshold_critical" = "70",
                        "rdsc_bdb_ingress_bytes_threshold_critical" = "1073741824",
                        "rdsc_bdb_egress_bytes_threshold_critical" = "1073741824",
                        "rdsc_node_ingress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_egress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_cpu_idle_threshold_critical" = "30",
                        "rdsc_proxy_cpu_threshold_critical" = "70",
                        "notification_channel" : "@slack-agl-alerts  @webhook-DD-Squadcast-Integration",
                        "roster": "@slack-agl-alerts",
                        "query" : ""
                      },
                      { 
                        "service_name" : "agl",
                        "component_name" : "agl-core-playback",
                        "priority" : 2,
                        "message" : "Redis Cloud Alert triggered",
                        "runbook" : "https://sony-liv.atlassian.net/wiki/x/BAJdHQ",
                        "query_time_window": "last_2m",
                        "rdsc_bdb_avg_latency_threshold_critical" = "5",
                        "rdsc_redis_used_memory_threshold_critical" = "26843545600",
                        "rdsc_bdb_shard_cpu_use_threshold_critical" = "70",
                        "rdsc_bdb_ingress_bytes_threshold_critical" = "1073741824",
                        "rdsc_bdb_egress_bytes_threshold_critical" = "1073741824",
                        "rdsc_node_ingress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_egress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_cpu_idle_threshold_critical" = "30",
                        "rdsc_proxy_cpu_threshold_critical" = "70",
                        "notification_channel" : "@slack-agl-alerts  @webhook-DD-Squadcast-Integration",
                        "roster": "@slack-agl-alerts",
                        "query" : ""
                      },
                      { 
                        "service_name" : "agl",
                        "component_name" : "agl-core-umsps",
                        "priority" : 2,
                        "message" : "Redis Cloud Alert triggered",
                        "runbook" : "https://sony-liv.atlassian.net/wiki/x/BAJdHQ",
                        "query_time_window": "last_2m",
                        "rdsc_bdb_avg_latency_threshold_critical" = "5",
                        "rdsc_redis_used_memory_threshold_critical" = "26843545600",
                        "rdsc_bdb_shard_cpu_use_threshold_critical" = "70",
                        "rdsc_bdb_ingress_bytes_threshold_critical" = "1073741824",
                        "rdsc_bdb_egress_bytes_threshold_critical" = "1073741824",
                        "rdsc_node_ingress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_egress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_cpu_idle_threshold_critical" = "30",
                        "rdsc_proxy_cpu_threshold_critical" = "70",
                        "notification_channel" : "@slack-agl-alerts  @webhook-DD-Squadcast-Integration",
                        "roster": "@slack-agl-alerts",
                        "query" : ""
                      },
                      { 
                        "service_name" : "b2b",
                        "component_name" : "b2b-prod-catalog-redis",
                        "priority" : 2,
                        "message" : "Redis Cloud Alert triggered",
                        "runbook" : "https://sony-liv.atlassian.net/wiki/x/BAJdHQ",
                        "query_time_window": "last_2m",
                        "rdsc_bdb_avg_latency_threshold_critical" = "5",
                        "rdsc_redis_used_memory_threshold_critical" = "26843545600",
                        "rdsc_bdb_shard_cpu_use_threshold_critical" = "70",
                        "rdsc_bdb_ingress_bytes_threshold_critical" = "1073741824",
                        "rdsc_bdb_egress_bytes_threshold_critical" = "1073741824",
                        "rdsc_node_ingress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_egress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_cpu_idle_threshold_critical" = "30",
                        "rdsc_proxy_cpu_threshold_critical" = "70",
                        "notification_channel" : "@slack-spni_prod_b2b_alerts  @webhook-DD-Squadcast-Integration",
                        "roster": "@slack-spni_prod_b2b_alerts",
                        "query" : ""
                      },
                      { 
                        "service_name" : "b2b",
                        "component_name" : "b2b-prod-playback-redis",
                        "priority" : 2,
                        "message" : "Redis Cloud Alert triggered",
                        "runbook" : "https://sony-liv.atlassian.net/wiki/x/BAJdHQ",
                        "query_time_window": "last_2m",
                        "rdsc_bdb_avg_latency_threshold_critical" = "5",
                        "rdsc_redis_used_memory_threshold_critical" = "26843545600",
                        "rdsc_bdb_shard_cpu_use_threshold_critical" = "70",
                        "rdsc_bdb_ingress_bytes_threshold_critical" = "1073741824",
                        "rdsc_bdb_egress_bytes_threshold_critical" = "1073741824",
                        "rdsc_node_ingress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_egress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_cpu_idle_threshold_critical" = "30",
                        "rdsc_proxy_cpu_threshold_critical" = "70",
                        "notification_channel" : "@slack-spni_prod_b2b_alerts   @webhook-DD-Squadcast-Integration",
                        "roster": "@slack-spni_prod_b2b_alerts",
                        "query" : ""
                      },
                      { 
                        "service_name" : "b2b",
                        "component_name" : "b2b-prod-subscription-redis",
                        "priority" : 2,
                        "message" : "Redis Cloud Alert triggered",
                        "runbook" : "https://sony-liv.atlassian.net/wiki/x/BAJdHQ",
                        "query_time_window": "last_2m",
                        "rdsc_bdb_avg_latency_threshold_critical" = "5",
                        "rdsc_redis_used_memory_threshold_critical" = "26843545600",
                        "rdsc_bdb_shard_cpu_use_threshold_critical" = "70",
                        "rdsc_bdb_ingress_bytes_threshold_critical" = "1073741824",
                        "rdsc_bdb_egress_bytes_threshold_critical" = "1073741824",
                        "rdsc_node_ingress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_egress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_cpu_idle_threshold_critical" = "30",
                        "rdsc_proxy_cpu_threshold_critical" = "70",
                        "notification_channel" : "@slack-spni_prod_b2b_alerts  @webhook-DD-Squadcast-Integration",
                        "roster": "@slack-spni_prod_b2b_alerts",
                        "query" : ""
                      },
                      { 
                        "service_name" : "sports-interactivity",
                        "component_name" : "si",
                        "priority" : 2,
                        "message" : "Redis Cloud Alert triggered",
                        "runbook" : "https://sony-liv.atlassian.net/wiki/x/BAJdHQ",
                        "query_time_window": "last_2m",
                        "rdsc_bdb_avg_latency_threshold_critical" = "5",
                        "rdsc_redis_used_memory_threshold_critical" = "26843545600",
                        "rdsc_bdb_shard_cpu_use_threshold_critical" = "70",
                        "rdsc_bdb_ingress_bytes_threshold_critical" = "1073741824",
                        "rdsc_bdb_egress_bytes_threshold_critical" = "1073741824",
                        "rdsc_node_ingress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_egress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_cpu_idle_threshold_critical" = "30",
                        "rdsc_proxy_cpu_threshold_critical" = "70",
                        "notification_channel" : "@slack-spni_prod_sports_interactvity_alerts  @webhook-DD-Squadcast-Integration",
                        "roster": "@slack-spni_prod_sports_interactvity_alerts",
                        "query" : ""
                      },
                      { 
                        "service_name" : "godavari",
                        "component_name" : "godavari-analytics-prod",
                        "priority" : 2,
                        "message" : "Redis Cloud Alert triggered",
                        "runbook" : "https://sony-liv.atlassian.net/wiki/x/BAJdHQ",
                        "query_time_window": "last_10m",
                        "rdsc_bdb_avg_latency_threshold_critical" = "5",
                        "rdsc_redis_used_memory_threshold_critical" = "26843545600",
                        "rdsc_bdb_shard_cpu_use_threshold_critical" = "70",
                        "rdsc_bdb_ingress_bytes_threshold_critical" = "1073741824",
                        "rdsc_bdb_egress_bytes_threshold_critical" = "1073741824",
                        "rdsc_node_ingress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_egress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_cpu_idle_threshold_critical" = "30",
                        "rdsc_proxy_cpu_threshold_critical" = "70",
                        "notification_channel" : "@slack-spni_prod_godavari_v1_alerts  @webhook-DD-Squadcast-Integration",
                        "roster": "@slack-spni_prod_godavari_v1_alerts",
                        "query" : ""
                      },
                      { 
                        "service_name" : "config-manager",
                        "component_name" : "pub-sub-redis",
                        "priority" : 2,
                        "message" : "Redis Cloud Alert triggered",
                        "runbook" : "https://sony-liv.atlassian.net/wiki/x/BAJdHQ",
                        "query_time_window": "last_2m",
                        "rdsc_bdb_avg_latency_threshold_critical" = "5",
                        "rdsc_redis_used_memory_threshold_critical" = "26843545600",
                        "rdsc_bdb_shard_cpu_use_threshold_critical" = "70",
                        "rdsc_bdb_ingress_bytes_threshold_critical" = "1073741824",
                        "rdsc_bdb_egress_bytes_threshold_critical" = "1073741824",
                        "rdsc_node_ingress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_egress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_cpu_idle_threshold_critical" = "30",
                        "rdsc_proxy_cpu_threshold_critical" = "70",
                        "notification_channel" : "@slack-spni_prod_config_manager_alerts  @webhook-DD-Squadcast-Integration",
                        "roster": "@slack-spni_prod_config_manager_alerts",
                        "query" : ""
                      },
                      { 
                        "service_name" : "es",
                        "component_name" : "search-bingewatch",
                        "priority" : 2,
                        "message" : "Redis Cloud Alert triggered",
                        "runbook" : "https://sony-liv.atlassian.net/wiki/x/BAJdHQ",
                        "query_time_window": "last_2m",
                        "rdsc_bdb_avg_latency_threshold_critical" = "5",
                        "rdsc_redis_used_memory_threshold_critical" = "26843545600",
                        "rdsc_bdb_shard_cpu_use_threshold_critical" = "70",
                        "rdsc_bdb_ingress_bytes_threshold_critical" = "1073741824",
                        "rdsc_bdb_egress_bytes_threshold_critical" = "1073741824",
                        "rdsc_node_ingress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_egress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_cpu_idle_threshold_critical" = "30",
                        "rdsc_proxy_cpu_threshold_critical" = "70",
                        "notification_channel" : "@slack-spni_prod_es_alerts  @webhook-DD-Squadcast-Integration",
                        "roster": "@slack-spni_prod_es_alerts",
                        "query" : ""
                      },
                      { 
                        "service_name" : "es",
                        "component_name" : "search-recommendation",
                        "priority" : 2,
                        "message" : "Redis Cloud Alert triggered",
                        "runbook" : "https://sony-liv.atlassian.net/wiki/x/BAJdHQ",
                        "query_time_window": "last_2m",
                        "rdsc_bdb_avg_latency_threshold_critical" = "5",
                        "rdsc_redis_used_memory_threshold_critical" = "26843545600",
                        "rdsc_bdb_shard_cpu_use_threshold_critical" = "70",
                        "rdsc_bdb_ingress_bytes_threshold_critical" = "1073741824",
                        "rdsc_bdb_egress_bytes_threshold_critical" = "1073741824",
                        "rdsc_node_ingress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_egress_bytes_max_threshold_critical" = "1073741824",
                        "rdsc_node_cpu_idle_threshold_critical" = "30",
                        "rdsc_proxy_cpu_threshold_critical" = "70",
                        "notification_channel" : "@slack-spni_prod_es_alerts  @webhook-DD-Squadcast-Integration",
                        "roster": "@slack-spni_prod_es_alerts",
                        "query" : ""
                      }                   
]
}