terraform {
    source = "../modules/WARROOM_METRICS_GV1"
}
# include {
#     path = find_in_parent_folders()
# }
locals {
    account = get_env("ACCOUNT_ID")
    datadog_module = get_env("DATADOG_MODULE")
}
remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }

  config = {
    bucket = "spn-terraform-tfstate"
    key = "${path_relative_to_include()}/${local.account}/${local.datadog_module}/terraform.tfstate"
    region         = "ap-south-1"
    encrypt        = true
    dynamodb_table = "terraform-lock-table"
   } 
}

inputs ={
# region = "ap-south-1"
datadog_site = "datadoghq.com"
spni_war_room_alert = [
              {
                "metric_name": "gv1.play_vsfb_u_live_show",
                "metric_keyword": "platform:android_phone",
                "priority": 1,
                "message": "(Play%+VSFB-U%) metric is high for platform:android_phone",
                "query_time_window": "last_1m",
                "monitor_thresholds": "80",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": "<",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.play_vsfb_u_live_show",
                "metric_keyword": "platform:jio_android_tv",
                "priority": 1,
                "message": "(Play%+VSFB-U%) metric is high for platform:jio_android_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "85.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": "<",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.play_vsfb_u_live_show",
                "metric_keyword": "platform:mweb",
                "priority": 1,
                "message": "(Play%+VSFB-U%) metric is high for platform:mweb",
                "query_time_window": "last_1m",
                "monitor_thresholds": "70",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": "<",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.play_vsfb_u_live_show",
                "metric_keyword": "platform:iphone",
                "priority": 1,
                "message": "(Play%+VSFB-U%) metric is high for platform:iphone",
                "query_time_window": "last_1m",
                "monitor_thresholds": "80.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": "<",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.play_vsfb_u_live_show",
                "metric_keyword": "platform:sony_android_tv",
                "priority": 1,
                "message": "(Play%+VSFB-U%) metric is high for platform:sony_android_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "82",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": "<",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.play_vsfb_u_live_show",
                "metric_keyword": "platform:web",
                "priority": 1,
                "message": "(Play%+VSFB-U%) metric is high for platform:web",
                "query_time_window": "last_1m",
                "monitor_thresholds": "80.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": "<",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.play_vsfb_u_live_show",
                "metric_keyword": "platform:xiaomi_android_tv",
                "priority": 1,
                "message": "(Play%+VSFB-U%) metric is high for platform:xiaomi_android_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "80.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": "<",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.play_vsfb_u_live_show",
                "metric_keyword": "platform:samsung_html_tv",
                "priority": 1,
                "message": "(Play%+VSFB-U%) metric is high for platform:samsung_html_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "85.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": "<",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.play_vsfb_u_live_show",
                "metric_keyword": "platform:fire_tv",
                "priority": 1,
                "message": "(Play%+VSFB-U%) metric is high for platform:fire_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "80.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": "<",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.play_vsfb_u_live_show",
                "metric_keyword": "platform:lg_html_tv",
                "priority": 1,
                "message": "(Play%+VSFB-U%) metric is high for platform:lg_html_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "85.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": "<",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.play_vsfb_u_live_show",
                "metric_keyword": "platform:android_tab",
                "priority": 1,
                "message": "(Play%+VSFB-U%) metric is high for platform:android_tab",
                "query_time_window": "last_1m",
                "monitor_thresholds": "77",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": "<",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.play_vsfb_u_live_show",
                "metric_keyword": "platform:ipad",
                "priority": 1,
                "message": "(Play%+VSFB-U%) metric is high for platform:ipad",
                "query_time_window": "last_1m",
                "monitor_thresholds": "82",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": "<",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.play_vsfb_u_live_show",
                "metric_keyword": "platform:apple_tv",
                "priority": 1,
                "message": "(Play%+VSFB-U%) metric is high for platform:apple_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "78.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": "<",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vsft_live_show",
                "metric_keyword": "platform:android_phone",
                "priority": 1,
                "message": "VSFT-U% metric is high for platform:android_phone",
                "query_time_window": "last_1m",
                "monitor_thresholds": "2",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vsft_live_show",
                "metric_keyword": "platform:jio_android_tv",
                "priority": 1,
                "message": "VSFT-U% metric is high for platform:jio_android_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vsft_live_show",
                "metric_keyword": "platform:mweb",
                "priority": 1,
                "message": "VSFT-U% metric is high for platform:mweb",
                "query_time_window": "last_1m",
                "monitor_thresholds": "2",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vsft_live_show",
                "metric_keyword": "platform:iphone",
                "priority": 1,
                "message": "VSFT-U% metric is high for platform:iphone",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vsft_live_show",
                "metric_keyword": "platform:sony_android_tv",
                "priority": 1,
                "message": "VSFT-U% metric is high for platform:sony_android_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vsft_live_show",
                "metric_keyword": "platform:web",
                "priority": 1,
                "message": "VSFT-U% metric is high for platform:web",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1.5",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vsft_live_show",
                "metric_keyword": "platform:xiaomi_android_tv",
                "priority": 1,
                "message": "VSFT-U% metric is high for platform:xiaomi_android_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1.5",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vsft_live_show",
                "metric_keyword": "platform:samsung_html_tv",
                "priority": 1,
                "message": "VSFT-U% metric is high for platform:samsung_html_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1.5",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vsft_live_show",
                "metric_keyword": "platform:fire_tv",
                "priority": 1,
                "message": "VSFT-U% metric is high for platform:fire_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1.5",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vsft_live_show",
                "metric_keyword": "platform:lg_html_tv",
                "priority": 1,
                "message": "VSFT-U% metric is high for platform:lg_html_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "2.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vsft_live_show",
                "metric_keyword": "platform:android_tab",
                "priority": 1,
                "message": "VSFT-U% metric is high for platform:android_tab",
                "query_time_window": "last_1m",
                "monitor_thresholds": "4",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vsft_live_show",
                "metric_keyword": "platform:ipad",
                "priority": 1,
                "message": "VSFT-U% metric is high for platform:ipad",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vsft_live_show",
                "metric_keyword": "platform:apple_tv",
                "priority": 1,
                "message": "VSFT-U% metric is high for platform:apple_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1.5",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vpft_live_show",
                "metric_keyword": "platform:android_phone",
                "priority": 1,
                "message": "VPFT% of play metric is high for platform:android_phone",
                "query_time_window": "last_1m",
                "monitor_thresholds": "4",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vpft_live_show",
                "metric_keyword": "platform:jio_android_tv",
                "priority": 1,
                "message": "VPFT% of play metric is high for platform:jio_android_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1.5",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vpft_live_show",
                "metric_keyword": "platform:mweb",
                "priority": 1,
                "message": "VPFT% of play metric is high for platform:mweb",
                "query_time_window": "last_1m",
                "monitor_thresholds": "3",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vpft_live_show",
                "metric_keyword": "platform:iphone",
                "priority": 1,
                "message": "VPFT% of play metric is high for platform:iphone",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1.5",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vpft_live_show",
                "metric_keyword": "platform:sony_android_tv",
                "priority": 1,
                "message": "VPFT% of play metric is high for platform:sony_android_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "2",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vpft_live_show",
                "metric_keyword": "platform:web",
                "priority": 1,
                "message": "VPFT% of play metric is high for platform:web",
                "query_time_window": "last_1m",
                "monitor_thresholds": "4.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vpft_live_show",
                "metric_keyword": "platform:xiaomi_android_tv",
                "priority": 1,
                "message": "VPFT% of play metric is high for platform:xiaomi_android_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "2.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vpft_live_show",
                "metric_keyword": "platform:samsung_html_tv",
                "priority": 1,
                "message": "VPFT% of play metric is high for platform:samsung_html_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1.5",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vpft_live_show",
                "metric_keyword": "platform:fire_tv",
                "priority": 1,
                "message": "VPFT% of play metric is high for platform:fire_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1.5",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vpft_live_show",
                "metric_keyword": "platform:lg_html_tv",
                "priority": 1,
                "message": "VPFT% of play metric is high for platform:lg_html_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1.5",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vpft_live_show",
                "metric_keyword": "platform:android_tab",
                "priority": 1,
                "message": "VPFT% of play metric is high for platform:android_tab",
                "query_time_window": "last_1m",
                "monitor_thresholds": "4",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vpft_live_show",
                "metric_keyword": "platform:ipad",
                "priority": 1,
                "message": "VPFT% of play metric is high for platform:ipad",
                "query_time_window": "last_1m",
                "monitor_thresholds": "2",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vpft_live_show",
                "metric_keyword": "platform:apple_tv",
                "priority": 1,
                "message": "VPFT% of play metric is high for platform:apple_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "2.5",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.avg_rebuff_live_show",
                "metric_keyword": "platform:android_phone",
                "priority": 1,
                "message": "Rebuff (Overall) metric is high for platform:android_phone",
                "query_time_window": "last_1m",
                "monitor_thresholds": "40",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.avg_rebuff_live_show",
                "metric_keyword": "platform:jio_android_tv",
                "priority": 1,
                "message": "Rebuff (Overall) metric is high for platform:jio_android_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.avg_rebuff_live_show",
                "metric_keyword": "platform:mweb",
                "priority": 1,
                "message": "Rebuff (Overall) metric is high for platform:mweb",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.avg_rebuff_live_show",
                "metric_keyword": "platform:iphone",
                "priority": 1,
                "message": "Rebuff (Overall) metric is high for platform:iphone",
                "query_time_window": "last_1m",
                "monitor_thresholds": "10.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.avg_rebuff_live_show",
                "metric_keyword": "platform:sony_android_tv",
                "priority": 1,
                "message": "Rebuff (Overall) metric is high for platform:sony_android_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "2",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.avg_rebuff_live_show",
                "metric_keyword": "platform:web",
                "priority": 1,
                "message": "Rebuff (Overall) metric is high for platform:web",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.avg_rebuff_live_show",
                "metric_keyword": "platform:xiaomi_android_tv",
                "priority": 1,
                "message": "Rebuff (Overall) metric is high for platform:xiaomi_android_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "3.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.avg_rebuff_live_show",
                "metric_keyword": "platform:samsung_html_tv",
                "priority": 1,
                "message": "Rebuff (Overall) metric is high for platform:samsung_html_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "2.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.avg_rebuff_live_show",
                "metric_keyword": "platform:fire_tv",
                "priority": 1,
                "message": "Rebuff (Overall) metric is high for platform:fire_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1.5",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.avg_rebuff_live_show",
                "metric_keyword": "platform:lg_html_tv",
                "priority": 1,
                "message": "Rebuff (Overall) metric is high for platform:lg_html_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "2.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.avg_rebuff_live_show",
                "metric_keyword": "platform:android_tab",
                "priority": 1,
                "message": "Rebuff (Overall) metric is high for platform:android_tab",
                "query_time_window": "last_1m",
                "monitor_thresholds": "40",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.avg_rebuff_live_show",
                "metric_keyword": "platform:ipad",
                "priority": 1,
                "message": "Rebuff (Overall) metric is high for platform:ipad",
                "query_time_window": "last_1m",
                "monitor_thresholds": "10",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.avg_rebuff_live_show",
                "metric_keyword": "platform:apple_tv",
                "priority": 1,
                "message": "Rebuff (Overall) metric is high for platform:apple_tv",
                "query_time_window": "last_1m",
                "monitor_thresholds": "2.0",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              },
              {
                "metric_name": "gv1.vpfb_live_show",
                "metric_keyword": "subscription_status:subscribed",
                "priority": 1,
                "message": "VPFB metric is high for platform:{{platform}} and content : {{content_id}} for subscribed users",
                "query_time_window": "last_1m",
                "monitor_thresholds": "1",
                "notification_channel": "@videoops@setindia.com @Videoops@multitvsolution.com @videooperations@multitvsolution.com",
                "operator": ">",
                "query": "",
                "group_by": "platform,content_id",
                "evaluation_delay": "720",
                "notify_nodata": false
              }
        ]
                }